export const FETCH_CHAT_HISTORY__REQUEST = 'FETCH_CHAT_HISTORY__REQUEST';
export const FETCH_CHAT_HISTORY__SUCCESS = 'FETCH_CHAT_HISTORY__SUCCESS';
export const FETCH_CHAT_HISTORY__FAILURE = 'FETCH_CHAT_HISTORY__FAILURE';