export const GOOGLE_SIGN_IN__REQUEST = 'GOOGLE_SIGN_IN__REQUEST';
export const GOOGLE_SIGN_IN__SUCCESS = 'GOOGLE_SIGN_IN__SUCCESS';
export const GOOGLE_SIGN_IN__FAILURE = 'GOOGLE_SIGN_IN__FAILURE';

export const GOOGLE_SIGN_OUT__REQUEST = 'GOOGLE_SIGN_OUT__REQUEST';
export const GOOGLE_SIGN_OUT__SUCCESS = 'GOOGLE_SIGN_OUT__SUCCESS';
export const GOOGLE_SIGN_OUT__FAILURE = 'GOOGLE_SIGN_OUT__FAILURE';

export const GITHUB_SIGN_IN__REQUEST = 'GITHUB_SIGN_IN__REQUEST';
export const GITHUB_SIGN_IN__SUCCESS = 'GITHUB_SIGN_IN__SUCCESS';
export const GITHUB_SIGN_IN__FAILURE = 'GITHUB_SIGN_IN__FAILURE';