export const FETCH_CHAT_HISTORY__REQUEST = 'FETCH_CHAT_HISTORY__REQUEST';
export const FETCH_CHAT_HISTORY__SUCCESS = 'FETCH_CHAT_HISTORY__SUCCESS';
export const FETCH_CHAT_HISTORY__FAILURE = 'FETCH_CHAT_HISTORY__FAILURE';

export const CREATE_CHAT = 'CREATE_CHAT';

export const ADD_USER_MESSAGE_TO_CHAT = 'ADD_USER_MESSAGE_TO_CHAT';

export const SEND_MESSAGE__REQUEST = 'SEND_MESSAGE__REQUEST';
export const SEND_MESSAGE__SUCCESS = 'SEND_MESSAGE__SUCCESS';
export const SEND_MESSAGE__FAILURE = 'SEND_MESSAGE__FAILURE';

export const UPDATE_CHAT_TITLE = 'UPDATE_CHAT_TITLE';

export const DELETE_CHAT = 'DELETE_CHAT';
