export const FETCH_CHAT_HISTORY__REQUEST = 'FETCH_CHAT_HISTORY__REQUEST';
export const FETCH_CHAT_HISTORY__SUCCESS = 'FETCH_CHAT_HISTORY__SUCCESS';
export const FETCH_CHAT_HISTORY__FAILURE = 'FETCH_CHAT_HISTORY__FAILURE';

export const CREATE_CHAT__REQUEST = 'CREATE_CHAT__REQUEST';
export const CREATE_CHAT__SUCCESS = 'CREATE_CHAT__SUCCESS';
export const CREATE_CHAT__FAILURE = 'CREATE_CHAT__FAILURE';