export const FETCH_CHAT_HISTORY__REQUEST = 'FETCH_CHAT_HISTORY__REQUEST';
export const FETCH_CHAT_HISTORY__SUCCESS = 'FETCH_CHAT_HISTORY__SUCCESS';
export const FETCH_CHAT_HISTORY__FAILURE = 'FETCH_CHAT_HISTORY__FAILURE';

export const CREATE_CHAT__REQUEST = 'CREATE_CHAT__REQUEST';
export const CREATE_CHAT__SUCCESS = 'CREATE_CHAT__SUCCESS';
export const CREATE_CHAT__FAILURE = 'CREATE_CHAT__FAILURE';

export const ADD_USER_MESSAGE_TO_CHAT = 'ADD_USER_MESSAGE_TO_CHAT';

export const SEND_MESSAGE__REQUEST = 'SEND_MESSAGE__REQUEST';
export const SEND_MESSAGE__SUCCESS = 'SEND_MESSAGE__SUCCESS';
export const SEND_MESSAGE__FAILURE = 'SEND_MESSAGE__FAILURE';